CREATE OR REPLACE VIEW XXHR_BUSINESS_GROUPS_VL AS
SELECT
  O.ORGANIZATION_ID ,
  OTL.NAME ,
  O.DATE_FROM ,
  O.DATE_TO
FROM
  HR_ALL_ORGANIZATION_UNITS O ,
  HR_ALL_ORGANIZATION_UNITS_TL OTL ,
  HR_ORGANIZATION_INFORMATION O2 ,
  HR_ORGANIZATION_INFORMATION O3 ,
  HR_ORGANIZATION_INFORMATION O4
WHERE
  O.ORGANIZATION_ID                = OTL.ORGANIZATION_ID
AND O.ORGANIZATION_ID              = O2.ORGANIZATION_ID (+)
AND O.ORGANIZATION_ID              = O3.ORGANIZATION_ID
AND O.ORGANIZATION_ID              = O4.ORGANIZATION_ID
AND O3.ORG_INFORMATION_CONTEXT     = 'Business Group Information'
AND O2.ORG_INFORMATION_CONTEXT (+) = 'Work Day Information'
AND O4.ORG_INFORMATION_CONTEXT     = 'CLASS'
AND O4.ORG_INFORMATION1            = 'HR_BG'
and o4.org_information2            = 'Y'
AND (o.date_to IS NULL OR o.date_to > SYSDATE);