package ch3.oracle.apps.xxhr.emp.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpSocitiesAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public EmpSocitiesAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("ch3.oracle.apps.xxhr.emp.server", /* package name */
      "EmpSocitiesAMLocal" /* Configuration Name */);
    }

    /**Container's getter for EmpSocietiesVO1
     */
    public OAViewObjectImpl getEmpSocietiesVO1() {
        return (OAViewObjectImpl)findViewObject("EmpSocietiesVO1");
    }
}
