package ch3.oracle.apps.xxhr.emp.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpSearchVORowImpl extends OAViewRowImpl {
    public static final int PERSONID = 0;
    public static final int FULLNAME = 1;
    public static final int EMPLOYEENUMBER = 2;
    public static final int EMAILADDRESS = 3;
    public static final int MGRFULLNAME = 4;
    public static final int MGREMPLOYEENUMBER = 5;
    public static final int MGREMAILADDRESS = 6;
    public static final int LASTUPDATEDBY = 7;
    public static final int LASTUPDATEDATE = 8;
    public static final int LASTUPDATELOGIN = 9;
    public static final int CREATIONDATE = 10;
    public static final int CREATEDBY = 11;
    public static final int SHOWHIDE = 12;
    public static final int EMPSOCIETIESVO = 13;

    /**This is the default constructor (do not remove)
     */
    public EmpSearchVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute EmailAddress
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute MgrFullName
     */
    public String getMgrFullName() {
        return (String) getAttributeInternal(MGRFULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MgrFullName
     */
    public void setMgrFullName(String value) {
        setAttributeInternal(MGRFULLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute MgrEmployeeNumber
     */
    public String getMgrEmployeeNumber() {
        return (String) getAttributeInternal(MGREMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MgrEmployeeNumber
     */
    public void setMgrEmployeeNumber(String value) {
        setAttributeInternal(MGREMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute MgrEmailAddress
     */
    public String getMgrEmailAddress() {
        return (String) getAttributeInternal(MGREMAILADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MgrEmailAddress
     */
    public void setMgrEmailAddress(String value) {
        setAttributeInternal(MGREMAILADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case FULLNAME:
            return getFullName();
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case EMAILADDRESS:
            return getEmailAddress();
        case MGRFULLNAME:
            return getMgrFullName();
        case MGREMPLOYEENUMBER:
            return getMgrEmployeeNumber();
        case MGREMAILADDRESS:
            return getMgrEmailAddress();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case SHOWHIDE:
            return getShowHide();
        case EMPSOCIETIESVO:
            return getEmpSocietiesVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SHOWHIDE:
            setShowHide((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link EmpSocietiesVO
     */
    public RowIterator getEmpSocietiesVO() {
        return (RowIterator)getAttributeInternal(EMPSOCIETIESVO);
    }


    /**Gets the attribute value for the calculated attribute ShowHide
     */
    public String getShowHide() {
        return (String) getAttributeInternal(SHOWHIDE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ShowHide
     */
    public void setShowHide(String value) {
        //setAttributeInternal(SHOWHIDE, value);
        populateAttribute(SHOWHIDE, value);        
    }
}
