EXECUTE ad_dd.register_table('XXHR', 'XXHR_PARTY_UPLOAD', 'T');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'TXN_ID',1, 'NUMBER', 38, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PARTY_TYPE', 2,'VARCHAR2', 30, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'ORG_NAME', 3,'VARCHAR2', 200, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PERSON_TITLE', 4,'VARCHAR2', 10, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PERSON_FIRST_NAME', 5, 'VARCHAR2', 100, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PERSON_LAST_NAME', 6, 'VARCHAR2', 100, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PHONE_TYPE', 7, 'VARCHAR2', 30, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'PHONE', 8, 'VARCHAR2', 40, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'EMAIL', 9, 'VARCHAR2', 200, 'Y', 'N');
EXECUTE AD_DD.REGISTER_COLUMN('XXHR', 'XXHR_PARTY_UPLOAD', 'ADDRESS_TYPE', 10, 'VARCHAR2', 30, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'ADDREXXHRSS_LINE_1', 11,'VARCHAR2', 240, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'ADDRESS_LINE_2', 12,'VARCHAR2', 240, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'ADDRESS_LINE_3', 13,'VARCHAR2', 240, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'CITY', 14,'VARCHAR2', 30, 'Y', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'COUNTY', 15,'VARCHAR2', 60, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'COUNTRY', 16,'VARCHAR2', 60, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'POSTAL_CODE', 17,'VARCHAR2', 30, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'TXN_STATUS', 18,'VARCHAR2', 30, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'TXN_MSG', 19,'VARCHAR2', 4000, 'N', 'N');
EXECUTE ad_dd.register_column('XXHR', 'XXHR_PARTY_UPLOAD', 'TXN_DATE', 20,'DATE', 30, 'N', 'N');
commit;